# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Motome\Views\MainWindow.ui'
#
# Created: Wed Dec 11 15:02:17 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        font = QtGui.QFont()
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/logo_320x320.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.omniBar = QtGui.QLineEdit(self.centralwidget)
        self.omniBar.setObjectName("omniBar")
        self.horizontalLayout.addWidget(self.omniBar)
        self.btnSettings = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.btnSettings.sizePolicy().hasHeightForWidth())
        self.btnSettings.setSizePolicy(sizePolicy)
        self.btnSettings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/cog.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon1)
        self.btnSettings.setFlat(True)
        self.btnSettings.setObjectName("btnSettings")
        self.horizontalLayout.addWidget(self.btnSettings)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.notesList = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.notesList.sizePolicy().hasHeightForWidth())
        self.notesList.setSizePolicy(sizePolicy)
        self.notesList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notesList.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.EditKeyPressed)
        self.notesList.setObjectName("notesList")
        self.verticalLayout_3.addWidget(self.notesList)
        self.btnMergeNotes = QtGui.QPushButton(self.layoutWidget)
        self.btnMergeNotes.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/page_white_stack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMergeNotes.setIcon(icon2)
        self.btnMergeNotes.setObjectName("btnMergeNotes")
        self.verticalLayout_3.addWidget(self.btnMergeNotes)
        self.toolBox = QtGui.QTabWidget(self.splitter)
        self.toolBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("")
        self.toolBox.setTabShape(QtGui.QTabWidget.Rounded)
        self.toolBox.setDocumentMode(True)
        self.toolBox.setObjectName("toolBox")
        self.tabEditor = QtGui.QWidget()
        self.tabEditor.setStyleSheet("")
        self.tabEditor.setObjectName("tabEditor")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabEditor)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.tabEditor)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.tagEdit = QtGui.QLineEdit(self.tabEditor)
        self.tagEdit.setObjectName("tagEdit")
        self.horizontalLayout_2.addWidget(self.tagEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.toolBox.addTab(self.tabEditor, "")
        self.tabPreview = QtGui.QWidget()
        self.tabPreview.setStyleSheet("")
        self.tabPreview.setObjectName("tabPreview")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabPreview)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notePreview = QtGui.QTextBrowser(self.tabPreview)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notePreview.sizePolicy().hasHeightForWidth())
        self.notePreview.setSizePolicy(sizePolicy)
        self.notePreview.setOpenLinks(False)
        self.notePreview.setObjectName("notePreview")
        self.verticalLayout.addWidget(self.notePreview)
        self.toolBox.addTab(self.tabPreview, "")
        self.tabDiff = QtGui.QWidget()
        self.tabDiff.setStyleSheet("")
        self.tabDiff.setObjectName("tabDiff")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabDiff)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.noteDiff = QtGui.QTextBrowser(self.tabDiff)
        self.noteDiff.setObjectName("noteDiff")
        self.verticalLayout_4.addWidget(self.noteDiff)
        self.toolBox.addTab(self.tabDiff, "")
        self.verticalLayout_5.addWidget(self.splitter)
        self.frameHistory = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameHistory.sizePolicy().hasHeightForWidth())
        self.frameHistory.setSizePolicy(sizePolicy)
        self.frameHistory.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameHistory.setFrameShadow(QtGui.QFrame.Raised)
        self.frameHistory.setObjectName("frameHistory")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frameHistory)
        self.horizontalLayout_4.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.historySlider = QtGui.QSlider(self.frameHistory)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historySlider.sizePolicy().hasHeightForWidth())
        self.historySlider.setSizePolicy(sizePolicy)
        self.historySlider.setMaximum(1)
        self.historySlider.setProperty("value", 1)
        self.historySlider.setTracking(True)
        self.historySlider.setOrientation(QtCore.Qt.Horizontal)
        self.historySlider.setObjectName("historySlider")
        self.horizontalLayout_4.addWidget(self.historySlider)
        self.btnPrevDate = QtGui.QPushButton(self.frameHistory)
        self.btnPrevDate.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/date_previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrevDate.setIcon(icon3)
        self.btnPrevDate.setObjectName("btnPrevDate")
        self.horizontalLayout_4.addWidget(self.btnPrevDate)
        self.btnNextDate = QtGui.QPushButton(self.frameHistory)
        self.btnNextDate.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/date_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNextDate.setIcon(icon4)
        self.btnNextDate.setObjectName("btnNextDate")
        self.horizontalLayout_4.addWidget(self.btnNextDate)
        self.btnMergeHistory = QtGui.QPushButton(self.frameHistory)
        self.btnMergeHistory.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/arrow_join.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMergeHistory.setIcon(icon5)
        self.btnMergeHistory.setObjectName("btnMergeHistory")
        self.horizontalLayout_4.addWidget(self.btnMergeHistory)
        self.verticalLayout_5.addWidget(self.frameHistory)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.omniBar, QtCore.SIGNAL("textChanged(QString)"), MainWindow.search_files)
        QtCore.QObject.connect(self.omniBar, QtCore.SIGNAL("returnPressed()"), MainWindow.new_note)
        QtCore.QObject.connect(self.historySlider, QtCore.SIGNAL("valueChanged(int)"), MainWindow.load_old_note)
        QtCore.QObject.connect(self.btnSettings, QtCore.SIGNAL("clicked()"), MainWindow.load_settings)
        QtCore.QObject.connect(self.btnPrevDate, QtCore.SIGNAL("clicked()"), MainWindow.click_older_date)
        QtCore.QObject.connect(self.btnNextDate, QtCore.SIGNAL("clicked()"), MainWindow.click_newer_date)
        QtCore.QObject.connect(self.btnMergeHistory, QtCore.SIGNAL("clicked()"), MainWindow.click_merge_history)
        QtCore.QObject.connect(self.btnMergeNotes, QtCore.SIGNAL("clicked()"), MainWindow.click_merge_notes)
        QtCore.QObject.connect(self.tagEdit, QtCore.SIGNAL("textChanged(QString)"), MainWindow.start_save)
        QtCore.QObject.connect(self.notesList, QtCore.SIGNAL("clicked(QModelIndex)"), MainWindow.click_update_ui_views)
        QtCore.QObject.connect(self.notesList, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.click_update_ui_views)
        QtCore.QObject.connect(self.notePreview, QtCore.SIGNAL("anchorClicked(QUrl)"), MainWindow.load_anchor)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.omniBar, self.notesList)
        MainWindow.setTabOrder(self.notesList, self.toolBox)
        MainWindow.setTabOrder(self.toolBox, self.btnPrevDate)
        MainWindow.setTabOrder(self.btnPrevDate, self.btnNextDate)
        MainWindow.setTabOrder(self.btnNextDate, self.historySlider)
        MainWindow.setTabOrder(self.historySlider, self.btnMergeNotes)
        MainWindow.setTabOrder(self.btnMergeNotes, self.tagEdit)
        MainWindow.setTabOrder(self.tagEdit, self.btnMergeHistory)
        MainWindow.setTabOrder(self.btnMergeHistory, self.btnSettings)
        MainWindow.setTabOrder(self.btnSettings, self.noteDiff)
        MainWindow.setTabOrder(self.noteDiff, self.notePreview)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.omniBar.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Search... Press Enter to create a new note with your seach as the title", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSettings.setToolTip(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMergeNotes.setToolTip(QtGui.QApplication.translate("MainWindow", "Merge & export notes in list", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Tags: ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tabEditor), QtGui.QApplication.translate("MainWindow", "Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tabPreview), QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setTabText(self.toolBox.indexOf(self.tabDiff), QtGui.QApplication.translate("MainWindow", "Diff", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrevDate.setToolTip(QtGui.QApplication.translate("MainWindow", "Older", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNextDate.setToolTip(QtGui.QApplication.translate("MainWindow", "Newer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMergeHistory.setToolTip(QtGui.QApplication.translate("MainWindow", "Diff history", None, QtGui.QApplication.UnicodeUTF8))

import MainWindow_rc
