# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Motome\Views\MergeNotesDialog.ui'
#
# Created: Thu Jan 02 11:56:56 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MergeNotesDialog(object):
    def setupUi(self, MergeNotesDialog):
        MergeNotesDialog.setObjectName("MergeNotesDialog")
        MergeNotesDialog.resize(600, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/logo_320x320.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MergeNotesDialog.setWindowIcon(icon)
        self.verticalLayout_3 = QtGui.QVBoxLayout(MergeNotesDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtGui.QSplitter(MergeNotesDialog)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnUpList = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpList.sizePolicy().hasHeightForWidth())
        self.btnUpList.setSizePolicy(sizePolicy)
        self.btnUpList.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUpList.setIcon(icon1)
        self.btnUpList.setObjectName("btnUpList")
        self.gridLayout.addWidget(self.btnUpList, 0, 1, 1, 1)
        self.btnDownList = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDownList.sizePolicy().hasHeightForWidth())
        self.btnDownList.setSizePolicy(sizePolicy)
        self.btnDownList.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDownList.setIcon(icon2)
        self.btnDownList.setObjectName("btnDownList")
        self.gridLayout.addWidget(self.btnDownList, 1, 1, 1, 1)
        self.notesList = QtGui.QListWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.notesList.sizePolicy().hasHeightForWidth())
        self.notesList.setSizePolicy(sizePolicy)
        self.notesList.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.notesList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.notesList.setObjectName("notesList")
        self.gridLayout.addWidget(self.notesList, 0, 0, 2, 1)
        self.toolBox = QtGui.QToolBox(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.pageNotes = QtGui.QWidget()
        self.pageNotes.setGeometry(QtCore.QRect(0, 0, 578, 281))
        self.pageNotes.setObjectName("pageNotes")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pageNotes)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.pageNotes)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.mergedNoteTitle = QtGui.QLineEdit(self.pageNotes)
        self.mergedNoteTitle.setObjectName("mergedNoteTitle")
        self.horizontalLayout_2.addWidget(self.mergedNoteTitle)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.btnMergeNotes = QtGui.QPushButton(self.pageNotes)
        self.btnMergeNotes.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resources/arrow_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMergeNotes.setIcon(icon3)
        self.btnMergeNotes.setObjectName("btnMergeNotes")
        self.verticalLayout_2.addWidget(self.btnMergeNotes)
        self.textMergedNotes = QtGui.QTextBrowser(self.pageNotes)
        self.textMergedNotes.setObjectName("textMergedNotes")
        self.verticalLayout_2.addWidget(self.textMergedNotes)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.pageNotes)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.mergedNoteTags = QtGui.QLineEdit(self.pageNotes)
        self.mergedNoteTags.setObjectName("mergedNoteTags")
        self.horizontalLayout.addWidget(self.mergedNoteTags)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.toolBox.addItem(self.pageNotes, "")
        self.pagePreview = QtGui.QWidget()
        self.pagePreview.setGeometry(QtCore.QRect(0, 0, 578, 281))
        self.pagePreview.setObjectName("pagePreview")
        self.verticalLayout = QtGui.QVBoxLayout(self.pagePreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnExportHtml = QtGui.QPushButton(self.pagePreview)
        self.btnExportHtml.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resources/html.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportHtml.setIcon(icon4)
        self.btnExportHtml.setObjectName("btnExportHtml")
        self.gridLayout_2.addWidget(self.btnExportHtml, 0, 0, 1, 1)
        self.btnPrintMergedPreview = QtGui.QPushButton(self.pagePreview)
        self.btnPrintMergedPreview.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resources/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrintMergedPreview.setIcon(icon5)
        self.btnPrintMergedPreview.setObjectName("btnPrintMergedPreview")
        self.gridLayout_2.addWidget(self.btnPrintMergedPreview, 0, 1, 1, 1)
        self.textMergedPreview = QtGui.QTextBrowser(self.pagePreview)
        self.textMergedPreview.setObjectName("textMergedPreview")
        self.gridLayout_2.addWidget(self.textMergedPreview, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.toolBox.addItem(self.pagePreview, "")
        self.verticalLayout_3.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(MergeNotesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(MergeNotesDialog)
        self.toolBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), MergeNotesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), MergeNotesDialog.reject)
        QtCore.QObject.connect(self.btnUpList, QtCore.SIGNAL("clicked()"), MergeNotesDialog.click_note_up)
        QtCore.QObject.connect(self.btnDownList, QtCore.SIGNAL("clicked()"), MergeNotesDialog.click_note_down)
        QtCore.QObject.connect(self.btnExportHtml, QtCore.SIGNAL("clicked()"), MergeNotesDialog.click_export_html)
        QtCore.QObject.connect(self.btnPrintMergedPreview, QtCore.SIGNAL("clicked()"), MergeNotesDialog.click_print)
        QtCore.QObject.connect(self.btnMergeNotes, QtCore.SIGNAL("clicked()"), MergeNotesDialog.click_merge_notes)
        QtCore.QMetaObject.connectSlotsByName(MergeNotesDialog)

    def retranslateUi(self, MergeNotesDialog):
        MergeNotesDialog.setWindowTitle(QtGui.QApplication.translate("MergeNotesDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpList.setToolTip(QtGui.QApplication.translate("MergeNotesDialog", "Move note up", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDownList.setToolTip(QtGui.QApplication.translate("MergeNotesDialog", "Move note down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MergeNotesDialog", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.mergedNoteTitle.setPlaceholderText(QtGui.QApplication.translate("MergeNotesDialog", "Enter a title for the merged note", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMergeNotes.setToolTip(QtGui.QApplication.translate("MergeNotesDialog", "Merge notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MergeNotesDialog", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageNotes), QtGui.QApplication.translate("MergeNotesDialog", "Merged Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportHtml.setToolTip(QtGui.QApplication.translate("MergeNotesDialog", "Export to HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrintMergedPreview.setToolTip(QtGui.QApplication.translate("MergeNotesDialog", "Print the merged notes", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pagePreview), QtGui.QApplication.translate("MergeNotesDialog", "Merged Preview", None, QtGui.QApplication.UnicodeUTF8))

import MergeNotesDialog_rc
