"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os
from setuptools import setup

from Motome.config import VERSION

APP = ['./Motome.py']
DATA_FILES = []
PY2APP_PLIST = {'CFBundleShortVersionString': VERSION}
PY2APP_OPTIONS = {'argv_emulation': True,
           'resources':'./Motome/styles',
           'iconfile':'./deployment/Icons/logo.icns',
           'plist': PY2APP_PLIST}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': PY2APP_OPTIONS},
    setup_requires=['py2app'],
)
